# Generated by Django 4.2.10 on 2024-03-23 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='approved',
        ),
    ]
